services:
  # ========== API GATEWAY ==========
  api_gateway:
    image: traefik:v3.0
    container_name: api_gateway
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=andres.lujanf@pucp.edu.pe"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--log.level=INFO"
      - "--log.format=json"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--global.sendanonymoususage=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard de Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - traefik_logs:/var/log/traefik
    networks:
      - red_cloud
    restart: unless-stopped
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"

  # ========== CONTENEDORES APIS ==========
  # API de Autenticación y Autorización
  auth_api:
    build:
      context: ./auth_api
      dockerfile: Dockerfile
    container_name: auth_api
    environment:
      - DB_HOST=usuarios_db
      - DB_PORT=3306
      - DB_NAME=usuarios_db
      - DB_USER=app_user
      - DB_PASSWORD=app_password123
      - JWT_SECRET_KEY=mi_clave_secreta_super_segura_12345
    depends_on:
      - usuarios_db
    networks:
      - red_cloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-api.entrypoints=websecure"
      - "traefik.http.routers.auth-api.tls.certresolver=myresolver"
      - "traefik.http.services.auth-api.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
      - "traefik.http.routers.auth-api.middlewares=auth-strip"
    restart: unless-stopped
  
  # API de Monitoreo de métricas
  monitoring_api:
    image: prom/prometheus:latest
    container_name: monitoring_api
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring_api/prometheus.yml:/etc/prometheus/prometheus.yml
      - metrics_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=2GB'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.enable-remote-write-receiver'
      - '--web.external-url=http://localhost/prometheus/'
      - '--web.route-prefix=/prometheus/'
    networks:
      - red_cloud
    extra_hosts:
      - "head-linux:192.168.203.1"
      - "head-openstack:192.168.204.1"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
  
  # API de Dashboard de métricas y logs
  dashboards_api:
    image: grafana/grafana:latest
    container_name: dashboards_api
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboards/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./dashboards/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - red_cloud
    restart: unless-stopped
    depends_on:
      - monitoring_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  # API Gestor de Imágenes
  image_manager_api:
    build:
      context: ./image_manager_api
      dockerfile: Dockerfile
    container_name: image_manager_api
    environment:
      - JWT_SECRET_KEY=mi_clave_secreta_super_segura_12345
      - IMAGES_DIR=/var/lib/images
      - DB_HOST=imagenes_db
      - DB_PORT=3306
      - DB_NAME=imagenes_db
      - DB_USER=images_user
      - DB_PASSWORD=images_pass123
    volumes:
      - images_data:/var/lib/images
    networks:
      - red_cloud
    extra_hosts:
      - "cluster-linux:192.168.203.1"
      - "cluster-openstack:192.168.204.1"
    depends_on:
      - imagenes_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.image-manager.rule=PathPrefix(`/images`)"
      - "traefik.http.routers.image-manager.entrypoints=websecure"
      - "traefik.http.routers.image-manager.tls.certresolver=myresolver"
      - "traefik.http.services.image-manager.loadbalancer.server.port=5700"
      - "traefik.http.middlewares.image-manager-strip.stripprefix.prefixes=/images"
      - "traefik.http.routers.image-manager.middlewares=image-manager-strip"
    restart: unless-stopped

  # API Slice Manager
  slice_manager_api:
    build:
      context: ./slice_manager_api
      dockerfile: Dockerfile
    container_name: slice_manager_api
    environment:
      - JWT_SECRET_KEY=mi_clave_secreta_super_segura_12345
      - IMAGE_MANAGER_URL=http://image_manager_api:5700
      - IMAGE_MANAGER_TOKEN=clavesihna
      - DRIVERS_URL=http://drivers:6200
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - DB_HOST=slices_db
      - DB_PORT=3306
      - DB_NAME=slices_db
      - DB_USER=slices_user
      - DB_PASSWORD=slices_pass123
    networks:
      - red_cloud
    depends_on:
      - image_manager_api
      - slices_db
      - rabbitmq
      - drivers
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.slice-manager.rule=PathPrefix(`/app`)"
      - "traefik.http.routers.slice-manager.entrypoints=websecure"
      - "traefik.http.routers.slice-manager.tls.certresolver=myresolver"
      - "traefik.http.services.slice-manager.loadbalancer.server.port=5900"
      - "traefik.http.middlewares.slice-manager-strip.stripprefix.prefixes=/app"
      - "traefik.http.routers.slice-manager.middlewares=slice-manager-strip"
    restart: unless-stopped

  # API VM Placement - Asignación de Workers (Consumer RabbitMQ)
  vm_placement_api:
    build:
      context: ./vm_placement_api
      dockerfile: Dockerfile
    container_name: vm_placement_api
    environment:
      - SERVICE_TOKEN=clavesihna
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - DRIVERS_URL=http://drivers:6200
      - DB_HOST=slices_db
      - DB_PORT=3306
      - DB_NAME=slices_db
      - DB_USER=slices_user
      - DB_PASSWORD=slices_pass123
      - PROMETHEUS_URL=http://monitoring_api:9090/prometheus
    volumes:
      - placement_tracking:/app/placement_tracking
    networks:
      - red_cloud
    depends_on:
      - rabbitmq
      - slices_db
      - drivers
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vm-placement.rule=PathPrefix(`/placement`)"
      - "traefik.http.routers.vm-placement.entrypoints=websecure"
      - "traefik.http.routers.vm-placement.tls.certresolver=myresolver"
      - "traefik.http.services.vm-placement.loadbalancer.server.port=6000"
      - "traefik.http.middlewares.vm-placement-strip.stripprefix.prefixes=/placement"
      - "traefik.http.routers.vm-placement.middlewares=vm-placement-strip"
    restart: unless-stopped

  # Networking & Security - Configuración de red (Consumer RabbitMQ)
  net_sec_api:
    build:
      context: ./net_sec_api
      dockerfile: Dockerfile
    container_name: net_sec_api
    environment:
      - SERVICE_TOKEN=clavesihna
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - DB_HOST=slices_db
      - DB_PORT=3306
      - DB_NAME=slices_db
      - DB_USER=slices_user
      - DB_PASSWORD=slices_pass123
      - SG_DB_HOST=security_groups_db
      - SG_DB_PORT=3306
      - SG_DB_NAME=security_groups_db
      - SG_DB_USER=secgroups_user
      - SG_DB_PASSWORD=secgroups_pass123
    networks:
      - red_cloud
    depends_on:
      - rabbitmq
      - slices_db
      - security_groups_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.net-sec.rule=PathPrefix(`/netsec`)"
      - "traefik.http.routers.net-sec.entrypoints=websecure"
      - "traefik.http.routers.net-sec.tls.certresolver=myresolver"
      - "traefik.http.services.net-sec.loadbalancer.server.port=6300"
      - "traefik.http.middlewares.net-sec-strip.stripprefix.prefixes=/netsec"
      - "traefik.http.routers.net-sec.middlewares=net-sec-strip"
    restart: unless-stopped

  # Drivers - Bypass para despliegue en clusters
  drivers:
    build:
      context: ./drivers
      dockerfile: Dockerfile
    container_name: drivers
    environment:
      - SERVICE_TOKEN=clavesihna
      - DB_HOST=slices_db
      - DB_PORT=3306
      - DB_NAME=slices_db
      - DB_USER=slices_user
      - DB_PASSWORD=slices_pass123
      - SG_DB_HOST=security_groups_db
      - SG_DB_PORT=3306
      - SG_DB_NAME=security_groups_db
      - SG_DB_USER=secgroups_user
      - SG_DB_PASSWORD=secgroups_pass123
    networks:
      - red_cloud
    extra_hosts:
      - "orquestador-linux:192.168.203.2"
    depends_on:
      - slices_db
      - security_groups_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drivers.rule=PathPrefix(`/drivers`)"
      - "traefik.http.routers.drivers.entrypoints=websecure"
      - "traefik.http.routers.drivers.tls.certresolver=myresolver"
      - "traefik.http.services.drivers.loadbalancer.server.port=6200"
      - "traefik.http.middlewares.drivers-strip.stripprefix.prefixes=/drivers"
      - "traefik.http.routers.drivers.middlewares=drivers-strip"
    restart: unless-stopped

  # ========== CONTENEDORES COMPLEMENTARIOS A LAS APIS ==========

  # RabbitMQ - Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - red_cloud
    restart: unless-stopped

  # cAdvisor - Métricas de la red de contenedores
  monitoring_docker_network:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring_docker_network
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - red_cloud
    restart: unless-stopped
  
  # Loki - Almacenamiento de logs
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    volumes:
      - loki_data:/loki
      - ./logs/loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - red_cloud
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=PathPrefix(`/loki`)"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.tls.certresolver=myresolver"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"

  # Promtail - Recolector de logs
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./logs/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - red_cloud
    restart: unless-stopped
    depends_on:
      - loki

  # ========== CONTENEDORES BASE DE DATOS ==========
  # Base de datos de usuarios
  usuarios_db:
    image: mysql:8.0
    container_name: usuarios_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - users_data:/var/lib/mysql
      - ./databases/init_usuarios.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_cloud
    restart: unless-stopped

  # Base de datos de imágenes
  imagenes_db:
    image: mysql:8.0
    container_name: imagenes_db
    command: --max_allowed_packet=1073741824
    environment:
      MYSQL_ROOT_PASSWORD: imagenes_root_pass
      MYSQL_DATABASE: imagenes_db
      MYSQL_USER: images_user
      MYSQL_PASSWORD: images_pass123
    volumes:
      - images_db_data:/var/lib/mysql
      - ./databases/init_imagenes.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_cloud
    restart: unless-stopped

  # Base de datos de slices
  slices_db:
    image: mysql:8.0
    container_name: slices_db
    environment:
      MYSQL_ROOT_PASSWORD: slices_root_password_123
      MYSQL_DATABASE: slices_db
      MYSQL_USER: slices_user
      MYSQL_PASSWORD: slices_pass123
    volumes:
      - slices_data:/var/lib/mysql
      - ./databases/init_slices.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_cloud
    restart: unless-stopped

  # Base de datos para Security Groups
  security_groups_db:
    image: mysql:8.0
    container_name: security_groups_db
    environment:
      MYSQL_ROOT_PASSWORD: secgroups_root_password_123
      MYSQL_DATABASE: security_groups_db
      MYSQL_USER: secgroups_user
      MYSQL_PASSWORD: secgroups_pass123
    volumes:
      - security_groups_data:/var/lib/mysql
      - ./databases/init_security_groups.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_cloud
    restart: unless-stopped

networks:
  red_cloud:
    driver: bridge

volumes:
  users_data:
  slices_data:
  security_groups_data:
  metrics_data:
  grafana_data:
  images_data:
  images_db_data:
  traefik_letsencrypt:
  traefik_logs:
  loki_data:
  placement_tracking:
