global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus se monitorea a sí mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas del head node (nodo actual)
  - job_name: 'node-exporter-headnode'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # Métricas de contenedores Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s

  # Métricas de los worker nodes
  - job_name: 'worker-nodes'
    static_configs:
      - targets: ['10.0.10.2:9100']
        labels:
          nombre: 'Worker-1'
          
      - targets: ['10.0.10.3:9100']
        labels:
          nombre: 'Worker-2'
          
      - targets: ['10.0.10.4:9100']
        labels:
          nombre: 'Worker-3'
    scrape_interval: 15s

  # Métricas de las APIs (si implementas /metrics endpoint)
  - job_name: 'apis'
    static_configs:
      - targets: ['auth_api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s