global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'openstack'
    headnode: '192.168.204.1'

# Enviar métricas al Prometheus Central
remote_write:
  - url: 'http://10.20.12.169:9090/prometheus/api/v1/write'
    queue_config:
      capacity: 10000
      max_shards: 5
      min_shards: 1
      max_samples_per_send: 5000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms

rule_files:
  # - rules.yml

scrape_configs:
  # Prometheus - Métricas del propio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas de los worker nodes
  - job_name: 'workers-openstack'
    static_configs:
      - targets: ['192.168.202.2:9100']
        labels:
          nombre: 'Worker-4'
          zona: 'openstack'
          
      - targets: ['192.168.202.3:9100']
        labels:
          nombre: 'Worker-5'
          zona: 'openstack'
          
      - targets: ['192.168.202.4:9100']
        labels:
          nombre: 'Worker-6'
          zona: 'openstack'
    scrape_interval: 15s

  # Blackbox Exporter - Para verificar el estado de workers en Cluster Openstack
  - job_name: 'blackbox-workers-openstack'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 192.168.202.2
          - 192.168.202.3
          - 192.168.202.4
        labels:
          zona: 'openstack'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.204.1:9115
