services:
  # ========== CONTENEDORES APIS ==========
  # API de Monitoreo de m√©tricas Cluster Openstack
  monitoring_api:
    image: prom/prometheus:latest
    container_name: monitoring_api
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./monitoring_api/prometheus.yml:/etc/prometheus/prometheus.yml
      - metrics_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=2GB'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'

volumes:
  metrics_data:
    driver: local
