version: '3.8'

services:
  # ========== CONTENEDORES APIS ==========
  # API del orquestador
  orquestador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orquestador_api
    restart: always
    network_mode: "host"
    environment:
      - MONGODB_URL=mongodb://localhost:27017/vncs_db
      - PYTHONUNBUFFERED=1
    depends_on:
      vncs_bd:
        condition: service_healthy
    volumes:
      - ./orquestador_api.py:/app/orquestador_api.py
      - ./vnc_manager.py:/app/vnc_manager.py

  # ========== CONTENEDORES BASE DE DATOS ==========
  # Base de datos de puertos VNC
  vncs_bd:
    image: mongo:7.0
    container_name: vncs_bd
    restart: always
    network_mode: "host"
    environment:
      MONGO_INITDB_DATABASE: vncs_db
    volumes:
      - vncs_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  vncs_data:
    driver: local
